-- For configuration changes that persists between updates
DTAP_ZONE_CONFIG = {
    ["y"] = 0,
    ["x"] = 0,
    ["h"] = 0,
    ["w"] = 0
}
DTAP_ZONE_FORWARD = {
    ["y"] = 0,
    ["x"] = 0.33333333333333,
    ["h"] = 1,
    ["w"] = 0.625
}
SEARCH_PATH = true
DKOPTREADER_CONFIG_LINE_SPACING = 1.2
DCREREADER_CONFIG_FONT_SIZES = {
    [1] = 12,
    [2] = 16,
    [3] = 20,
    [4] = 22,
    [5] = 24,
    [6] = 26,
    [7] = 28,
    [8] = 30,
    [9] = 34,
    [10] = 38,
    [11] = 44
}
DLANDSCAPE_CLOCKWISE_ROTATION = true
DCREREADER_CONFIG_DEFAULT_FONT_SIZE = 22
DKOPTREADER_CONFIG_RENDER_QUALITY = 1
DCREREADER_CONFIG_MARGIN_SIZES_SMALL = {
    [1] = 5,
    [2] = 10,
    [3] = 5,
    [4] = 10
}
FRONTLIGHT_SENSITIVITY_DECREASE = 2
SEARCH_LIBRARY_PATH  = "/mnt/onboard"
DCREREADER_CONFIG_MARGIN_SIZES_LARGE = {
    [1] = 20,
    [2] = 20,
    [3] = 20,
    [4] = 20
}
KOBO_LIGHT_ON_START = -2
SEARCH_AUTHORS = true
DKOPTREADER_CONFIG_DETECT_INDENT = 1
DBACKGROUND_COLOR = 0
DKOPTREADER_CONFIG_AUTO_STRAIGHTEN = 0
DKOPTREADER_CONFIG_CONTRAST = 1
DOVERLAPPIXELS = 30
DMINIBAR_HEIGHT = 7
DRENDER_MODE = 0
DMINIBAR_FONT_SIZE = 14
DKOPTREADER_CONFIG_TEXT_WRAP = 0
DCREREADER_CONFIG_MARGIN_SIZES_MEDIUM = {
    [1] = 10,
    [2] = 15,
    [3] = 10,
    [4] = 15
}
DHINTCOUNT = 1
DKOPTREADER_CONFIG_DEFAULT_WORD_SPACING = -0.2
DDOUBLE_TAP_ZONE_PREV_CHAPTER = {
    ["y"] = 0,
    ["x"] = 0,
    ["h"] = 0.25,
    ["w"] = 0.25
}
DCREREADER_CONFIG_LINE_SPACE_PERCENT_MEDIUM = 100
SEARCH_TAGS = true
DCREREADER_VIEW_MODE = "page"
DKOPTREADER_CONFIG_JUSTIFICATION = 3
DMINIBAR_CONTAINER_HEIGHT = 14
DSCROLL_MODE = 0
DUSE_TURBO_LIB = false
KOBO_SYNC_BRIGHTNESS_WITH_NICKEL = true
DCREREADER_CONFIG_LINE_SPACE_PERCENT_SMALL = 90
DTAP_ZONE_BACKWARD = {
    ["y"] = 0,
    ["x"] = 0.125,
    ["h"] = 1,
    ["w"] = 0.20833333333333
}
DKOPTREADER_CONFIG_MAX_COLUMNS = 2
SEARCH_TITLE = true
DKOPTREADER_CONFIG_DOC_LANGS_CODE = {
    [1] = "eng",
    [2] = "chi_sim"
}
DCREREADER_PROGRESS_BAR = 1
DGLOBAL_CACHE_SIZE_MAXIMUM = 62914560
SEARCH_CASESENSITIVE = false
DRCOUNTMAX = 6
DDICT_FONT_SIZE = 20
ANDROID_FONT_DIR = "/system/fonts;/sdcard/koreader/fonts"
DOUTER_PAGE_COLOR = 0
DTAP_ZONE_BOOKMARK = {
    ["y"] = 0,
    ["x"] = 0.875,
    ["h"] = 0.125,
    ["w"] = 0.125
}
DCREREADER_CONFIG_DEFAULT_FONT_GAMMA = 15
DKOPTREADER_CONFIG_DOC_LANGS_TEXT = {
    [1] = "English",
    [2] = "Chinese"
}
DCREREADER_CONFIG_LIGHTER_FONT_GAMMA = 10
DGLOBAL_CACHE_SIZE_MINIMUM = 10485760
DKOPTREADER_CONFIG_TRIM_PAGE = 1
DKOPTREADER_CONFIG_PAGE_MARGIN = 0.1
SEARCH_SERIES = true
SEARCH_LIBRARY_PATH2 = ""
DKOPTREADER_CONFIG_DEFECT_SIZE = 1
DTAP_ZONE_FLIPPING = {
    ["y"] = 0,
    ["x"] = 0,
    ["h"] = 0.125,
    ["w"] = 0.125
}
DMINIBAR_TOC_MARKER_WIDTH = 2
DKOPTREADER_CONFIG_FONT_SIZE = 1
DDOUBLE_TAP_ZONE_NEXT_CHAPTER = {
    ["y"] = 0,
    ["x"] = 0.75,
    ["h"] = 0.25,
    ["w"] = 0.25
}
FOLLOW_LINK_TIMEOUT = 0.5
DTAP_ZONE_MENU = {
    ["y"] = 0,
    ["x"] = 0.125,
    ["h"] = 0.25,
    ["w"] = 0.75
}
DKOPTREADER_CONFIG_DOC_DEFAULT_LANG_CODE = "eng"
DKOPTREADER_CONFIG_WORD_SPACINGS = {
    [1] = 0.05,
    [2] = -0.2,
    [3] = 0.375
}
DFULL_SCREEN = 1
DGLOBAL_CACHE_FREE_PROPORTION = 0.4
DCREREADER_TWO_PAGE_THRESHOLD = 7
DALPHA_SORT_CASE_INSENSITIVE = true
DCREREADER_CONFIG_LINE_SPACE_PERCENT_LARGE = 120
DGLOBALGAMMA = 1
DCREREADER_CONFIG_DARKER_FONT_GAMMA = 25
DSHOWOVERLAP = false
DCHANGE_WEST_SWIPE_TO_EAST = false
DTAP_ZONE_MINIBAR = {
    ["y"] = 0.9375,
    ["x"] = 0,
    ["h"] = 0.0625,
    ["w"] = 1
}
DSHOWHIDDENFILES = false
DCHANGE_EAST_SWIPE_TO_WEST = false
